### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by robmarkcole** [statueofmike/rtsp#10]
Hi 
I did a bit of googling to discover that authenticated RTSP streams can be accessed with a modified url of form 
```python
RTSP_URL = f"rtsp://{USERNAME}:{PASSWORD}@192.168.1.221:554/11"
```
This could be included in your readme or just left here as an issue :-)

**Comment by dactylroot** [comment]
Good idea, I'll add to the readme.

--
Michael
