### ISSUE TITLE
Can't Set CV_CAP_PROP_BUFFERSIZE

### ISSUE THREAD

**Issue by dactylroot** [statueofmike/rtsp#13]
### Problem
Given an unknown source framerate and unknown frame processing time for each frame, we want to be able to always grab the most recent frame at the time of a `read()` call. In contrast to traditional process-every-frame stream workflows, which **opencv-python** seems to have been designed  around.

Ideally we could follow `cap.set(CV_CAP_PROP_BUFFERSIZE,1)` and then always have the most recent frame available. Unfortunately, contrary to [this suggestion](https://stackoverflow.com/a/30032945/1949791), we don't appear to be able to set this property in Python:

    In : cap.set(cv2.CAP_PROP_BUFFERSIZE,1)                                                                                  
    Out: False

It appears everyone tries to manually flush the buffer themselves e.g. [1](https://answers.opencv.org/question/91077/delay-when-grabbing-frames-from-webcam/?answer=91113#post-id-91113) [2a](https://github.com/opencv/opencv/issues/10671) [2b](https://answers.opencv.org/question/183162/delay-in-frame-grabbing-with-opencv3-and-ubuntu-1604/) 

### Current Workaround
As a workaround, I parameterized the buffer skipping rate. So users of this package still have to be conscious of their source framerate and set a flush rate accordingly.

### Possible Solutions
Some options to consider to fix this:
 * Find out how to set the `CAP_PROP_BUFFERSIZE` property for OpenCV.
 * Use another thread to spool frames as quickly as possible. This is no ideal as we don't want to force every user into multithreading situations, especially when OpenCV supposedly has this capability already.

**Comment by Mauhing** [comment]
I have also notice that `cv2.CAP_PROP_BUFFERSIZE,1)` does not work. What I am doing right now is to constantly `cv2.grab()` and only retrieve when I need it. However, this is not a good solution.

**Comment by davidlrobinson** [comment]
This seems feature seems essential for live machine learning workflows.

**Comment by ghost** [comment]
On my Raspberry Pi project, `cv2.CAP_PROP_BUFFERSIZE, 1` does actually work, but it means there's still a buffer of 1 that needs to be cleared before `read`ing a live image. `cv2.CAP_PROP_BUFFERSIZE, 0` is what I have been trying to get to work, and it does work on my Mac and Windows PCs.

**Comment by dactylroot** [comment]
Closing as this is an OpenCV issue
