### ISSUE TITLE
module "rtsp" has no attribute "Client"

### ISSUE THREAD

**Issue by OussamaBATOUCHE** [statueofmike/rtsp#22]
I'm trying to use this module to read RTSP stream, I tried with the exemple in your readme (One-off Retrieval)
and I got this error : 
**AttributeError: module 'rtsp' has no attribute 'Client'.**

Environment: 

-     - Jetson TX2
-     - Ubuntu 18.04 LTS
-     - Python 3.6.9

**Comment by inzel** [comment]
I have this same issue. Any fixes?

**Comment by inzel** [comment]
I figured out that this was caused by me having a test file named rtsp.py in the same directory so it was trying to import from that. Renamed it and the issue went away
