### ISSUE TITLE
How can I get NTP time

### ISSUE THREAD

**Issue by Hobeom** [statueofmike/rtsp#23]
how can I get NTP(Absolute TIMESTAMP) information using cv2 video capture

**Comment by dactylroot** [comment]
Hi @HoBeom can you try accessing the cv2 capture directly via `client._stream` ?

**Comment by dactylroot** [comment]
@HoBeom for example, try `import cv2; client._stream.get(cv2.CAP_PROP_POS_MSEC)/1000`
