### ISSUE TITLE
object has no attribute 'save'

### ISSUE THREAD

**Issue by yaba** [statueofmike/rtsp#28]
I've just found this package and was running the sample code.

I'm getting "object has no attribute 'save'" although the camera show as connected:

> Connected to video source rtsp://xxxx:xxxx@x.x.x.x/.
> Traceback (most recent call last):
>   File "d:\Dev\Python\Rtsp2email\rtsp2mail.py", line 9, in <module>
>     rclient.read().save("./"+ str(datetime.datetime.now()) +".jpg")
>     ^^^^^^^^^^^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'save'

**Comment by dactylroot** [comment]
Hi @yaba ,

Can you try to see what is being returned from that `read()` call?

e.g. `im = rclient.read(); print(type(im))`

**Comment by yaba** [comment]
Connected to video source rtsp://xxx:xxx@x.x.x/.
<class 'NoneType'>

EDIT: Forgot to add that I'm testing on Windows, let me check on Linux also.

**Comment by dactylroot** [comment]
Unless there's been a change to OpenCV I don't know yet, it seems like an RTSP or OpenCV issue.

For some reason, no image is being retrieved at all.

What does it say when you use `verbose=True` while making the client?

**Comment by yaba** [comment]
I'm using it. On Linux output is basically the same:

```
Connected to video source rtsp://xx:xx@x.x.x.x/.
<class 'NoneType'>
FATAL: exception not rethrown
Aborted
```

**Comment by yaba** [comment]
Think I got it, by checking a similar issue with the error thrown on Linux. 

Adding a time.sleep(3) between the rtsp.Client and client.read() fixes the issue, maybe some timeout while connecting to the camera and 'rtsp' doesn't handle it?

**Comment by dactylroot** [comment]
ahh I see. I should probably put that into the README. It was more a **"minimal working example"** than to be copy and pasted into a script.

**Comment by yaba** [comment]
Nice work BTW, easier than working around cv2 :) Thanks.
