### ISSUE TITLE
[Question] Would an asyncio rtsp stream reader make sense?

### ISSUE THREAD

**Issue by pawarren** [statueofmike/rtsp#7]
In the docs, you say: "v2.0.0 - lightweight native-Python implementation rtsp client functions"

Are you thinking of using asyncio/concurrency to handle concurrent RTSP streams?

I'm experimenting with different ways of listening to dozens of cameras concurrently and was curious what a native Python solution might look like :)

**Comment by dactylroot** [comment]
My current plan is to remove the OpenCV dependency while relying on ffmpeg for media manipulation (my idea of "lightweight").

Unfortunately, this is not a project that gets my full attention often, and I'm currently still implementing the basic RTSP network functions.

To try to answer your question: `asyncio` might be necessary just to manage a single stream properly. I haven't used `asyncio` before, but it looks like a nice alternative to direct subprocess and thread management and I'll be happy to look into it more for my own benefit. I have always used Python's `subprocess` and `threading` but a more structured framework like `asyncio` would probably help a lot in terms of maintainability and debugging.

My plan is for this `rtsp` library to manage a single stream and leave applications using it to deal with multi-stream, CDN, and broadcasting protocol features.

Are you looking for more of a user-facing application, like [Shinobi](https://shinobi.video/)? I don't plan to make a full-featured media player here, keeping to the scope of the `rtsp` package name.
