### ISSUE TITLE
Get the byteArray 

### ISSUE THREAD

**Issue by CostGranda** [statueofmike/rtsp#8]
Hello, first thanks for your project and effort put on this.

I'm currently developing a script for FacialRecognition and the APIs that I'm using receive the ByteArray of the image capture using RTSP. I'm wonder if you can guide me how can I achieve this. Actually I have noticed that the `read()` method return the image in Pillow format, maybe I should touch your code to change this, but can't find where.

Thank you so much.

**Comment by dactylroot** [comment]
`pandas` and other data packages can typically perform array conversions from PIL formats. e.g. `numpy.as_array(my-pil-image)`
